services:
  app:
    build: ./docker
    image: php:8.3.12-fpm
    container_name: php_app
    working_dir: /var/www
    volumes:
      - ./memory_cards:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: nginx_web
    working_dir: /var/www
    volumes:
      - ./memory_cards:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2222
      MYSQL_DATABASE: memcards
      MYSQL_USER: memcards_user
      MYSQL_PASSWORD: 3333
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data: